version: '3.4'

services:
  dockerwebapp:
    image: dockerwebapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
